### PR TITLE
Adds Feature Native SSO (https://developer.okta.com/docs/guides/configure-native-sso/main/)

### PR DESCRIPTION
**Pull request by emanor-okta**
#### Description:
:seedling: Adds support for EA feature [Native SSO Token Exchange](https://developer.okta.com/docs/guides/configure-native-sso/main)

#### Testing details:
- [X]  Verified basic functionality of change
- [ ]  Added tests 

#### Other considerations:
- [X] Has security implications
- [ ] Has UX changes

#### Changes
AppAuth
OktaOidc
Example App

### CODE REVIEW

**Comment by oleggnidets-okta** [comment]
Hi @emanor-okta 
The PR looks good to me, but I'm not sure whether we introduce this feature in our SDK. @mikenachbaur-okta @robertdamphousse-okta Do we have this feature requested? Should we merge it?

**Comment by jjlangholtz** [comment]
Any updates on whether this feature will be included in the SDK? Since native SSO is now generally available, are there plans to resume this work and release in an updated SDK version?

**Comment by emanor-okta** [comment]
> 
[This](https://developer.okta.com/blog/2021/11/12/native-sso) blog post might help

**Comment by jjlangholtz** [comment]
@emanor-okta Thanks for the link. So it looks like it's possible to implement the device secret flow with the existing SDK but with quite a lot of boilerplate. I think it would be valuable to include a convenience method for this flow like you have in this MR.

That would also simplify adding an additional helper method for the React Native SDK.

**Comment by glebus** [comment]
Why this cool feature hasn't merge yet?

**Comment by mikenachbaur-okta** [comment]
For anyone interested in trying out this functionality, we just released the first public beta of a new suite of SDKs here to address this, and other authentication challenges with the current OIDC SDK.

https://github.com/okta/okta-mobile-swift

The new functionality being focused around TokenExchangeFlow, and can be easy to use as you can see through [the sample code](https://github.com/okta/okta-mobile-swift/blob/master/Samples/AuthenticationFlows.swift#L88).

We welcome any and all feedback (notes on how to submit feedback in the projects README).

**Comment by mikenachbaur-okta** [comment]
This has been implemented in the new okta-mobile-swift, so as a result I'll be closing this issue out.

**Pull request closed without merging**
